stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY: 900461047507.dkr.ecr.eu-central-1.amazonaws.com
  DOCKER_APP_NAME: jira-work

build for production:
  stage: build
  before_script:
    - kubectl get cm ${DOCKER_APP_NAME}-production-yml -o jsonpath='{.data}' --namespace=production |  yq e -P | tail -n +2 | sed -r 's/^.{2}//' > config.yml
  script:
    - docker build --build-arg DOCKER_REGISTRY=${DOCKER_REGISTRY} -t ${DOCKER_REGISTRY}/${DOCKER_APP_NAME}:${CI_COMMIT_SHORT_SHA} .
    - docker push ${DOCKER_REGISTRY}/${DOCKER_APP_NAME}:${CI_COMMIT_SHORT_SHA}
  rules:
    - when: manual

deploy to production:
  stage: deploy
  needs: [ "build for production" ]
  script:
    - helm upgrade --install --atomic --timeout 5m --namespace=production --set image.tag=${CI_COMMIT_SHORT_SHA} --set env=production ${DOCKER_APP_NAME} ./helm --debug