stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY: 900461047507.dkr.ecr.eu-central-1.amazonaws.com
  DOCKER_APP_NAME: jira-work
  NAMESPACE: tools

build :
  stage: build
  script:
    - docker build --build-arg DOCKER_REGISTRY=${DOCKER_REGISTRY} -t ${DOCKER_REGISTRY}/${DOCKER_APP_NAME}:${CI_COMMIT_SHORT_SHA} .
    - docker push ${DOCKER_REGISTRY}/${DOCKER_APP_NAME}:${CI_COMMIT_SHORT_SHA}
  rules:
    - when: manual

deploy:
  stage: deploy
  needs: [ "build" ]
  script:
    - curl -H "X-Vault-Token:${VAULT_TOKEN}" ${VAULT_ADDR} | jq -r '.data.data | keys[] as $key | "\($key)=\(.[$key])"' > ~/tmp_env/${DOCKER_APP_NAME}-${NAMESPACE}-env.yaml
    - kubectl create cm ${DOCKER_APP_NAME}-${NAMESPACE}-yaml --namespace ${NAMESPACE} --from-env-file ~/tmp_env//${DOCKER_APP_NAME}-${NAMESPACE}-env.yaml --dry-run=client -o yaml | kubectl apply -f - && rm ~/tmp_env/${DOCKER_APP_NAME}-${NAMESPACE}-env.yaml
    - helm upgrade --install --atomic --timeout 5m --namespace=${NAMESPACE} --set image.tag=${CI_COMMIT_SHORT_SHA} --set env=${NAMESPACE} ${DOCKER_APP_NAME} ./helm --debug